name: _
environment:
  sdk: ">=3.13.0-0 <4.0.0"
  flutter: ">=3.47.0-0"
workspace:
  - create
  - docs_snippets
  - forui
  - forui_cli
  - forui_hooks
  - forui_internal_gen
  - forui_lucide
  - forui_phosphor
  - spotlight

dev_dependencies:
  flint: ^2.16.2
