name: forui
description: >-
  Beautifully designed, minimalistic Flutter widgets for desktop & touch devices. Designs are heavily
  inspired by shadcn/ui and are fully customizable.
version: 0.24.3
homepage: https://forui.dev/
documentation: https://forui.dev/docs
repository: https://github.com/duobaseio/forui/tree/main/forui
issue_tracker: https://github.com/duobaseio/forui/issues
topics:
  - user-interface
  - design-system
  - shadcn-ui
  - components
  - widget
screenshots:
  - description: "A collection of beautifully designed, minimalistic widgets for desktop & touch devices."
    path: screenshots/banner-text-130226.png

environment:
  sdk: ">=3.12.0-0 <4.0.0"
  flutter: ">=3.44.0-0"
resolution: workspace
workspace:
  - example

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  forui_assets: ^0.24.0
  intl: any
  meta: ^1.11.0
  sugar: ^4.0.0
  vector_math: ^2.1.4

dev_dependencies:
  build_runner: ^2.10.4
  flutter_test:
    sdk: flutter
  forui_internal_gen:
    git: https://github.com/duobaseio/forui.git
  leak_tracker_flutter_testing: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter.ttf
        - asset: assets/fonts/inter/Inter-Italic.ttf
          style: italic

  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
