// ignore_for_file: avoid_dynamic_calls

import 'dart:convert';
import 'dart:io';

final List<(String locale, String message)> locales = [
  ('af', 'Verwyder'),
  ('am', 'አስወግድ'),
  ('ar', 'إزالة'),
  ('as', 'আঁতৰাওক'),
  ('az', 'Silin'),
  ('be', 'Выдаліць'),
  ('bg', 'Премахване'),
  ('bn', 'সরান'),
  ('bs', 'Ukloni'),
  ('ca', 'Elimina'),
  ('cs', 'Odebrat'),
  ('cy', 'Tynnu'),
  ('da', 'Fjern'),
  ('de', 'Entfernen'),
  ('de_CH', 'Entfernen'),
  ('el', 'Κατάργηση'),
  ('en', 'Remove'),
  ('en_AU', 'Remove'),
  ('en_CA', 'Remove'),
  ('en_GB', 'Remove'),
  ('en_IE', 'Remove'),
  ('en_IN', 'Remove'),
  ('en_NZ', 'Remove'),
  ('en_SG', 'Remove'),
  ('en_ZA', 'Remove'),
  ('es', 'Quitar'),
  ('es_419', 'Quitar'),
  ('es_AR', 'Quitar'),
  ('es_BO', 'Quitar'),
  ('es_CL', 'Quitar'),
  ('es_CO', 'Quitar'),
  ('es_CR', 'Quitar'),
  ('es_DO', 'Quitar'),
  ('es_EC', 'Quitar'),
  ('es_GT', 'Quitar'),
  ('es_HN', 'Quitar'),
  ('es_MX', 'Quitar'),
  ('es_NI', 'Quitar'),
  ('es_PA', 'Quitar'),
  ('es_PE', 'Quitar'),
  ('es_PR', 'Quitar'),
  ('es_PY', 'Quitar'),
  ('es_SV', 'Quitar'),
  ('es_US', 'Quitar'),
  ('es_UY', 'Quitar'),
  ('es_VE', 'Quitar'),
  ('et', 'Eemalda'),
  ('eu', 'Kendu'),
  ('fa', 'حذف'),
  ('fi', 'Poista'),
  ('fil', 'Alisin'),
  ('fr', 'Retirer'),
  ('fr_CA', 'Retirer'),
  ('gl', 'Quitar'),
  ('gsw', 'Entfernen'),
  ('gu', 'દૂર કરો'),
  ('he', 'הסרה'),
  ('hi', 'हटाएं'),
  ('hr', 'Ukloni'),
  ('hu', 'Eltávolítás'),
  ('hy', 'Հեռացնել'),
  ('id', 'Hapus'),
  ('is', 'Fjarlægja'),
  ('it', 'Rimuovi'),
  ('ja', '削除'),
  ('ka', 'ამოშლა'),
  ('kk', 'Алып тастау'),
  ('km', 'យកចេញ'),
  ('kn', 'ತೆಗೆದುಹಾಕಿ'),
  ('ko', '제거'),
  ('ky', 'Алып салуу'),
  ('lo', 'ເອົາອອກ'),
  ('lt', 'Pašalinti'),
  ('lv', 'Noņemt'),
  ('mk', 'Отстрани'),
  ('ml', 'നീക്കംചെയ്യുക'),
  ('mn', 'Хасах'),
  ('mr', 'काढून टाका'),
  ('ms', 'Alih keluar'),
  ('my', 'ဖယ်ရှားရန်'),
  ('nb', 'Fjern'),
  ('ne', 'हटाउनुहोस्'),
  ('nl', 'Verwijderen'),
  ('no', 'Fjern'),
  ('or', 'ବାହାର କରନ୍ତୁ'),
  ('pa', 'ਹਟਾਓ'),
  ('pl', 'Usuń'),
  ('ps', 'لرې کول'),
  ('pt', 'Remover'),
  ('pt_PT', 'Remover'),
  ('ro', 'Eliminați'),
  ('ru', 'Удалить'),
  ('si', 'ඉවත් කරන්න'),
  ('sk', 'Odstrániť'),
  ('sl', 'Odstrani'),
  ('sq', 'Hiq'),
  ('sr', 'Уклони'),
  ('sr_Latn', 'Ukloni'),
  ('sv', 'Ta bort'),
  ('sw', 'Ondoa'),
  ('ta', 'அகற்று'),
  ('te', 'తీసివేయి'),
  ('th', 'นำออก'),
  ('tl', 'Alisin'),
  ('tr', 'Kaldır'),
  ('uk', 'Видалити'),
  ('ur', 'ہٹائیں'),
  ('uz', 'Olib tashlash'),
  ('vi', 'Xóa'),
  ('zh', '移除'),
  ('zh_HK', '移除'),
  ('zh_TW', '移除'),
  ('zu', 'Susa'),
];

void main() {
  // Replace with name of key to generate.
  const key = 'multiSelectTagSemanticsLabel';

  for (final (locale, value) in locales) {
    final arb = File('lib/l10n/f_$locale.arb');
    if (locale == 'en') {
      continue;
    }

    final data = json.decode(arb.readAsStringSync());
    data[key] = value;

    arb.writeAsStringSync(const JsonEncoder.withIndent('  ').convert(data));
  }
}
