// ignore_for_file: avoid_dynamic_calls

import 'dart:convert';
import 'dart:io';

final List<(String locale, String message)> locales = [
  ('af', 'Bladsy {page}'),
  ('am', 'ገፅ {page}'),
  ('ar', 'الصفحة {page}'),
  ('as', 'পৃষ্ঠা {page}'),
  ('az', 'Səhifə {page}'),
  ('be', 'Старонка {page}'),
  ('bg', 'Страница {page}'),
  ('bn', 'পৃষ্ঠা {page}'),
  ('bs', '{page}. stranica'),
  ('ca', 'Pàgina {page}'),
  ('cs', 'Stránka {page}'),
  ('cy', 'Tudalen {page}'),
  ('da', 'Side {page}'),
  ('de', 'Seite {page}'),
  ('de_CH', 'Seite {page}'),
  ('el', 'Σελίδα {page}'),
  ('en', 'Page {page}'),
  ('en_AU', 'Page {page}'),
  ('en_CA', 'Page {page}'),
  ('en_GB', 'Page {page}'),
  ('en_IE', 'Page {page}'),
  ('en_IN', 'Page {page}'),
  ('en_NZ', 'Page {page}'),
  ('en_SG', 'Page {page}'),
  ('en_ZA', 'Page {page}'),
  ('es', 'Página {page}'),
  ('es_419', 'Página {page}'),
  ('es_AR', 'Página {page}'),
  ('es_BO', 'Página {page}'),
  ('es_CL', 'Página {page}'),
  ('es_CO', 'Página {page}'),
  ('es_CR', 'Página {page}'),
  ('es_DO', 'Página {page}'),
  ('es_EC', 'Página {page}'),
  ('es_GT', 'Página {page}'),
  ('es_HN', 'Página {page}'),
  ('es_MX', 'Página {page}'),
  ('es_NI', 'Página {page}'),
  ('es_PA', 'Página {page}'),
  ('es_PE', 'Página {page}'),
  ('es_PR', 'Página {page}'),
  ('es_PY', 'Página {page}'),
  ('es_SV', 'Página {page}'),
  ('es_US', 'Página {page}'),
  ('es_UY', 'Página {page}'),
  ('es_VE', 'Página {page}'),
  ('et', '{page}. leht'),
  ('eu', '{page}. orria'),
  ('fa', 'صفحه {page}'),
  ('fi', 'Sivu {page}'),
  ('fil', 'Page {page}'),
  ('fr', 'Page {page}'),
  ('fr_CA', 'Page {page}'),
  ('gl', 'Páxina {page}'),
  ('gsw', 'Seite {page}'),
  ('gu', 'પેજ {page}'),
  ('he', 'דף {page}'),
  ('hi', 'पेज {page}'),
  ('hr', 'Stranica {page}'),
  ('hu', '{page}. oldal'),
  ('hy', 'Էջ {page}'),
  ('id', 'Halaman {page}'),
  ('is', 'Síða {page}'),
  ('it', 'Pagina {page}'),
  ('ja', '{page} ページ'),
  ('ka', 'გვერდი {page}'),
  ('kk', '{page}-бет'),
  ('km', 'ទំព័រ {page}'),
  ('kn', 'ಪುಟ {page}'),
  ('ko', '{page}페이지'),
  ('ky', '{page}-бет'),
  ('lo', 'ໜ້າ {page}'),
  ('lt', '{page} puslapis'),
  ('lv', '{page}. lapa'),
  ('mk', 'Страница {page}'),
  ('ml', 'പേജ് {page}'),
  ('mn', '{page}-р хуудас'),
  ('mr', 'पेज {page}'),
  ('ms', 'Halaman {page}'),
  ('my', 'စာမျက်နှာ {page}'),
  ('nb', 'Side {page}'),
  ('ne', 'पृष्ठ {page}'),
  ('nl', 'Pagina {page}'),
  ('no', 'Side {page}'),
  ('or', 'ପୃଷ୍ଠା {page}'),
  ('pa', 'ਪੰਨਾ {page}'),
  ('pl', 'Strona {page}'),
  ('ps', 'مخ {page}'),
  ('pt', 'Página {page}'),
  ('pt_PT', 'Página {page}'),
  ('ro', 'Pagina {page}'),
  ('ru', 'Страница {page}'),
  ('si', 'පිටුව {page}'),
  ('sk', 'Strana {page}'),
  ('sl', 'Stran {page}'),
  ('sq', 'Faqja {page}'),
  ('sr', '{page}. страница'),
  ('sr_Latn', '{page}. stranica'),
  ('sv', 'Sida {page}'),
  ('sw', 'Ukurasa {page}'),
  ('ta', 'பக்கம் {page}'),
  ('te', 'పేజీ {page}'),
  ('th', 'หน้า {page}'),
  ('tl', 'Page {page}'),
  ('tr', 'Sayfa {page}'),
  ('uk', 'Сторінка {page}'),
  ('ur', 'صفحہ {page}'),
  ('uz', '{page}-sahifa'),
  ('vi', 'Trang {page}'),
  ('zh', '第 {page} 页'),
  ('zh_HK', '第 {page} 頁'),
  ('zh_TW', '第 {page} 頁'),
  ('zu', 'Ikhasi {page}'),
];

void main() {
  // Replace with name of key to generate.
  const key = 'paginationPageSemanticsLabel';

  for (final (locale, value) in locales) {
    final arb = File('lib/l10n/f_$locale.arb');
    if (locale == 'en') {
      continue;
    }

    final data = json.decode(arb.readAsStringSync());
    data[key] = value;

    arb.writeAsStringSync(const JsonEncoder.withIndent('  ').convert(data));
  }
}
