// ignore_for_file: avoid_dynamic_calls

import 'dart:convert';
import 'dart:io';

final List<(String locale, String message)> locales = [
  ('af', 'Meer'),
  ('am', 'ተጨማሪ'),
  ('ar', 'المزيد'),
  ('as', 'অধিক'),
  ('az', 'Daha çox'),
  ('be', 'Больш'),
  ('bg', 'Още'),
  ('bn', 'আরও'),
  ('bs', 'Više'),
  ('ca', 'Més'),
  ('cs', 'Více'),
  ('cy', 'Rhagor'),
  ('da', 'Mere'),
  ('de', 'Mehr'),
  ('de_CH', 'Mehr'),
  ('el', 'Περισσότερα'),
  ('en', 'More'),
  ('en_AU', 'More'),
  ('en_CA', 'More'),
  ('en_GB', 'More'),
  ('en_IE', 'More'),
  ('en_IN', 'More'),
  ('en_NZ', 'More'),
  ('en_SG', 'More'),
  ('en_ZA', 'More'),
  ('es', 'Más'),
  ('es_419', 'Más'),
  ('es_AR', 'Más'),
  ('es_BO', 'Más'),
  ('es_CL', 'Más'),
  ('es_CO', 'Más'),
  ('es_CR', 'Más'),
  ('es_DO', 'Más'),
  ('es_EC', 'Más'),
  ('es_GT', 'Más'),
  ('es_HN', 'Más'),
  ('es_MX', 'Más'),
  ('es_NI', 'Más'),
  ('es_PA', 'Más'),
  ('es_PE', 'Más'),
  ('es_PR', 'Más'),
  ('es_PY', 'Más'),
  ('es_SV', 'Más'),
  ('es_US', 'Más'),
  ('es_UY', 'Más'),
  ('es_VE', 'Más'),
  ('et', 'Rohkem'),
  ('eu', 'Gehiago'),
  ('fa', 'بیشتر'),
  ('fi', 'Lisää'),
  ('fil', 'Higit pa'),
  ('fr', 'Plus'),
  ('fr_CA', 'Plus'),
  ('gl', 'Máis'),
  ('gsw', 'Meh'),
  ('gu', 'વધુ'),
  ('he', 'עוד'),
  ('hi', 'अधिक'),
  ('hr', 'Više'),
  ('hu', 'Továbbiak'),
  ('hy', 'Ավելին'),
  ('id', 'Lainnya'),
  ('is', 'Meira'),
  ('it', 'Altro'),
  ('ja', 'その他'),
  ('ka', 'მეტი'),
  ('kk', 'Тағы'),
  ('km', 'ច្រើនទៀត'),
  ('kn', 'ಇನ್ನಷ್ಟು'),
  ('ko', '더보기'),
  ('ky', 'Дагы'),
  ('lo', 'ເພີ່ມເຕີມ'),
  ('lt', 'Daugiau'),
  ('lv', 'Vairāk'),
  ('mk', 'Повеќе'),
  ('ml', 'കൂടുതൽ'),
  ('mn', 'Илүү'),
  ('mr', 'अधिक'),
  ('ms', 'Lagi'),
  ('my', 'နောက်ထပ်'),
  ('nb', 'Mer'),
  ('ne', 'थप'),
  ('nl', 'Meer'),
  ('no', 'Mer'),
  ('or', 'ଅଧିକ'),
  ('pa', 'ਹੋਰ'),
  ('pl', 'Więcej'),
  ('ps', 'نور'),
  ('pt', 'Mais'),
  ('pt_PT', 'Mais'),
  ('ro', 'Mai multe'),
  ('ru', 'Ещё'),
  ('si', 'තව'),
  ('sk', 'Viac'),
  ('sl', 'Več'),
  ('sq', 'Më shumë'),
  ('sr', 'Више'),
  ('sr_Latn', 'Više'),
  ('sv', 'Mer'),
  ('sw', 'Zaidi'),
  ('ta', 'மேலும்'),
  ('te', 'మరిన్ని'),
  ('th', 'เพิ่มเติม'),
  ('tl', 'Higit pa'),
  ('tr', 'Daha fazla'),
  ('uk', 'Більше'),
  ('ur', 'مزید'),
  ('uz', 'Yana'),
  ('vi', 'Thêm'),
  ('zh', '更多'),
  ('zh_HK', '更多'),
  ('zh_TW', '更多'),
  ('zu', 'Okuningi'),
];

void main() {
  // Replace with name of key to generate.
  const key = 'breadcrumbCollapsedSemanticsLabel';

  for (final (locale, value) in locales) {
    final arb = File('lib/l10n/f_$locale.arb');
    if (locale == 'en') {
      continue;
    }

    final data = json.decode(arb.readAsStringSync());
    data[key] = value;

    arb.writeAsStringSync(const JsonEncoder.withIndent('  ').convert(data));
  }
}
