import 'dart:io';

import 'package:analyzer/dart/analysis/analysis_context_collection.dart';
import 'package:analyzer/dart/analysis/results.dart';
import 'package:code_builder/code_builder.dart';
import 'package:path/path.dart' as p;

import '../main.dart';
import 'generate_icon_mapping.dart';
import 'generate_material_theme.dart';

String generateSnippets((Map<String, (String, String, String)>, Map<String, (String, String)>) mapped) {
  final sources = [
    for (final MapEntry(:key, value: (name, description, source)) in mapped.$1.entries)
      "'$key': ('$name', '$description', r'''$source''')",
  ];
  final init = [
    for (final MapEntry(:key, value: (name, source)) in mapped.$2.entries) "'$key': ('$name', r'''$source''')",
  ];

  final library = LibraryBuilder()
    ..comments.addAll([header])
    ..body.addAll([
      (FieldBuilder()
            ..docs.addAll(['/// All snippets. Generated by tool/main.dart.'])
            ..name = 'snippets'
            ..modifier = .constant
            ..assignment = Code('{\n  ${sources.join(',\n  ')}\n}'))
          .build(),
      (FieldBuilder()
            ..docs.addAll(['/// The main.dart snippets used by `dart forui init`. Generated by tool/main.dart.'])
            ..name = 'init'
            ..modifier = .constant
            ..assignment = Code('{\n  ${init.join(',\n  ')}\n}'))
          .build(),
    ]);

  return metaFormatter.format(library.build().accept(emitter).toString());
}

/// Traverses & maps the library and finds all targets to convert into snippets.
Future<(Map<String, (String, String, String)>, Map<String, (String, String)>)> mapSnippets(
  AnalysisContextCollection collection,
) async {
  final directory = p.join(Directory.current.parent.path, 'forui_cli', 'tool', 'snippets', 'literals');

  final files = Directory(
    library,
  ).listSync(recursive: true).whereType<File>().where((f) => f.path.endsWith('.dart')).map((f) => f.path).toList();

  final approximateMaterialThemeFinder = ToApproximateMaterialThemeFinder();
  for (final file in files) {
    if (await collection.contextFor(file).currentSession.getResolvedUnit(file) case final ResolvedUnitResult result) {
      result.unit.accept(approximateMaterialThemeFinder);
    }
  }

  final assetFiles = Directory(
    assetsLibrary,
  ).listSync(recursive: true).whereType<File>().where((f) => f.path.endsWith('.dart')).map((f) => f.path).toList();

  final iconFinder = IconsFinder();
  for (final file in assetFiles) {
    if (await collection.contextFor(file).currentSession.getResolvedUnit(file) case final ResolvedUnitResult result) {
      result.unit.accept(iconFinder);
    }
  }

  return (
    {
      'main-basic': (
        'main',
        'A minimal Forui app entry point',
        File(p.join(directory, 'main_basic.dart')).readAsStringSync(),
      ),
      'main-router': (
        'main',
        'A Forui app entry point using MaterialApp.router',
        File(p.join(directory, 'main_router.dart')).readAsStringSync(),
      ),
      materialThemeName: (
        materialThemeFile,
        'An extension mapping your Forui theme to a Material ThemeData',
        mapMaterialThemeMapping(approximateMaterialThemeFinder.snippet!),
      ),
      iconMappingName: (
        iconMappingFile,
        'An enum mapping Forui Lucide icons for lookup by name',
        mapIconMapping(iconFinder.icons),
      ),
    },
    {
      'basic': ('main', File(p.join(directory, 'main_basic_init.dart')).readAsStringSync()),
      'router': ('main', File(p.join(directory, 'main_router_init.dart')).readAsStringSync()),
    },
  );
}
