import 'package:flutter/widgets.dart';

import 'package:forui/forui.dart';
import 'package:forui_cli/forui_cli.dart';
import 'package:hugeicons/hugeicons.dart' as hugeicons;
import 'package:iconoir_flutter/iconoir_flutter.dart' as iconoir;
import 'package:remixicon/remixicon.dart' as remix;
import 'package:tabler_icons_plus/tabler_icons_plus.dart' as tabler;

/// A library-agnostic icon.
enum PreviewIcon {
  home,
  search,
  settings,
  bell,
  plus,
  ellipsis,
  chevronRight,
  play,
  skipForward,
  music,
  coffee,
  cart,
  creditCard,
  calendar,
  clock,
  users,
  upload,
  alertTriangle,
  info,
  check,
  x,
  lightbulb,
  blinds,
  wallet,
  layoutDashboard,
  arrowLeftRight,
  trendingUp,
  landmark,
  pieChart,
  target,
  barChart,
  fileText,
  user,
  shield,
  paintbrush,
  helpCircle,
  messageSquare,
  bookOpen,
  activity,
  circlePlus,
  camera,
  cloud,
  globe,
  gauge,
  repeat,
  refreshCw,
}

/// Injects the active [IconLibrary] so any descendant card can resolve a [PreviewIcon] to a concrete glyph without
/// knowing which library is selected.
class PreviewIcons extends InheritedWidget {
  /// The library that glyphs are drawn from.
  final IconLibrary library;

  /// The color applied when [icon] is called without an explicit color.
  final Color color;

  /// Creates a [PreviewIcons].
  const PreviewIcons({required this.library, required this.color, required super.child, super.key});

  /// The [PreviewIcons] enclosing [context].
  static PreviewIcons of(BuildContext context) {
    final icons = context.dependOnInheritedWidgetOfExactType<PreviewIcons>();
    assert(icons != null, 'No PreviewIcons ancestor found in the given context.');
    return icons!;
  }

  /// Resolves [icon] to a glyph widget.
  Widget icon(PreviewIcon icon, {double size = 20, Color? color}) {
    final tint = color ?? this.color;
    return switch (library) {
      .hugeicons => hugeicons.HugeIcon(icon: _huge(icon), color: tint, size: size),
      .lucide => Icon(_lucide(icon), size: size, color: tint),
      .tabler => Icon(_tabler(icon), size: size, color: tint),
      .remix => Icon(_remix(icon), size: size, color: tint),
      .iconoir => SizedBox.square(dimension: size, child: _iconoir(icon, tint, size)),
    };
  }

  @override
  bool updateShouldNotify(PreviewIcons old) => library != old.library || color != old.color;
}

List<List<dynamic>> _huge(PreviewIcon icon) => switch (icon) {
  .home => hugeicons.HugeIcons.strokeRoundedHome01,
  .search => hugeicons.HugeIcons.strokeRoundedSearch01,
  .settings => hugeicons.HugeIcons.strokeRoundedSettings02,
  .bell => hugeicons.HugeIcons.strokeRoundedNotification03,
  .plus => hugeicons.HugeIcons.strokeRoundedAdd01,
  .ellipsis => hugeicons.HugeIcons.strokeRoundedMoreHorizontal,
  .chevronRight => hugeicons.HugeIcons.strokeRoundedArrowRight01,
  .play => hugeicons.HugeIcons.strokeRoundedPlay,
  .skipForward => hugeicons.HugeIcons.strokeRoundedNext,
  .music => hugeicons.HugeIcons.strokeRoundedMusicNote03,
  .coffee => hugeicons.HugeIcons.strokeRoundedCoffee02,
  .cart => hugeicons.HugeIcons.strokeRoundedShoppingCart01,
  .creditCard => hugeicons.HugeIcons.strokeRoundedCreditCard,
  .calendar => hugeicons.HugeIcons.strokeRoundedCalendar03,
  .clock => hugeicons.HugeIcons.strokeRoundedClock01,
  .users => hugeicons.HugeIcons.strokeRoundedUserGroup,
  .upload => hugeicons.HugeIcons.strokeRoundedUpload03,
  .alertTriangle => hugeicons.HugeIcons.strokeRoundedAlert02,
  .info => hugeicons.HugeIcons.strokeRoundedInformationCircle,
  .check => hugeicons.HugeIcons.strokeRoundedTick02,
  .x => hugeicons.HugeIcons.strokeRoundedCancel01,
  .lightbulb => hugeicons.HugeIcons.strokeRoundedIdea,
  .blinds => hugeicons.HugeIcons.strokeRoundedBlinds,
  .wallet => hugeicons.HugeIcons.strokeRoundedWallet01,
  .layoutDashboard => hugeicons.HugeIcons.strokeRoundedDashboardSquare01,
  .arrowLeftRight => hugeicons.HugeIcons.strokeRoundedArrowDataTransferHorizontal,
  .trendingUp => hugeicons.HugeIcons.strokeRoundedChartUp,
  .landmark => hugeicons.HugeIcons.strokeRoundedBank,
  .pieChart => hugeicons.HugeIcons.strokeRoundedPieChart,
  .target => hugeicons.HugeIcons.strokeRoundedTarget01,
  .barChart => hugeicons.HugeIcons.strokeRoundedChartColumn,
  .fileText => hugeicons.HugeIcons.strokeRoundedFile02,
  .user => hugeicons.HugeIcons.strokeRoundedUser,
  .shield => hugeicons.HugeIcons.strokeRoundedShield01,
  .paintbrush => hugeicons.HugeIcons.strokeRoundedPaintBrush01,
  .helpCircle => hugeicons.HugeIcons.strokeRoundedHelpCircle,
  .messageSquare => hugeicons.HugeIcons.strokeRoundedMessage01,
  .bookOpen => hugeicons.HugeIcons.strokeRoundedBookOpen01,
  .activity => hugeicons.HugeIcons.strokeRoundedActivity01,
  .circlePlus => hugeicons.HugeIcons.strokeRoundedAddCircle,
  .camera => hugeicons.HugeIcons.strokeRoundedCamera01,
  .cloud => hugeicons.HugeIcons.strokeRoundedCloud,
  .globe => hugeicons.HugeIcons.strokeRoundedGlobal,
  .gauge => hugeicons.HugeIcons.strokeRoundedDashboardSpeed01,
  .repeat => hugeicons.HugeIcons.strokeRoundedRepeat,
  .refreshCw => hugeicons.HugeIcons.strokeRoundedRefresh,
};

IconData _lucide(PreviewIcon icon) => switch (icon) {
  .home => FLucideIcons.house,
  .search => FLucideIcons.search,
  .settings => FLucideIcons.settings,
  .bell => FLucideIcons.bell,
  .plus => FLucideIcons.plus,
  .ellipsis => FLucideIcons.ellipsis,
  .chevronRight => FLucideIcons.chevronRight,
  .play => FLucideIcons.play,
  .skipForward => FLucideIcons.skipForward,
  .music => FLucideIcons.music,
  .coffee => FLucideIcons.coffee,
  .cart => FLucideIcons.shoppingCart,
  .creditCard => FLucideIcons.creditCard,
  .calendar => FLucideIcons.calendar,
  .clock => FLucideIcons.clock,
  .users => FLucideIcons.users,
  .upload => FLucideIcons.upload,
  .alertTriangle => FLucideIcons.triangleAlert,
  .info => FLucideIcons.info,
  .check => FLucideIcons.check,
  .x => FLucideIcons.x,
  .lightbulb => FLucideIcons.lightbulb,
  .blinds => FLucideIcons.blinds,
  .wallet => FLucideIcons.wallet,
  .layoutDashboard => FLucideIcons.layoutDashboard,
  .arrowLeftRight => FLucideIcons.arrowLeftRight,
  .trendingUp => FLucideIcons.trendingUp,
  .landmark => FLucideIcons.landmark,
  .pieChart => FLucideIcons.pieChart,
  .target => FLucideIcons.target,
  .barChart => FLucideIcons.barChart,
  .fileText => FLucideIcons.fileText,
  .user => FLucideIcons.user,
  .shield => FLucideIcons.shield,
  .paintbrush => FLucideIcons.paintbrush,
  .helpCircle => FLucideIcons.helpCircle,
  .messageSquare => FLucideIcons.messageSquare,
  .bookOpen => FLucideIcons.bookOpen,
  .activity => FLucideIcons.activity,
  .circlePlus => FLucideIcons.circlePlus,
  .camera => FLucideIcons.camera,
  .cloud => FLucideIcons.cloud,
  .globe => FLucideIcons.globe,
  .gauge => FLucideIcons.gauge,
  .repeat => FLucideIcons.repeat,
  .refreshCw => FLucideIcons.refreshCw,
};

IconData _tabler(PreviewIcon icon) => switch (icon) {
  .home => tabler.TablerIcons.home,
  .search => tabler.TablerIcons.search,
  .settings => tabler.TablerIcons.settings,
  .bell => tabler.TablerIcons.bell,
  .plus => tabler.TablerIcons.plus,
  .ellipsis => tabler.TablerIcons.dots,
  .chevronRight => tabler.TablerIcons.chevronRight,
  .play => tabler.TablerIcons.playerPlay,
  .skipForward => tabler.TablerIcons.playerTrackNext,
  .music => tabler.TablerIcons.music,
  .coffee => tabler.TablerIcons.coffee,
  .cart => tabler.TablerIcons.shoppingCart,
  .creditCard => tabler.TablerIcons.creditCard,
  .calendar => tabler.TablerIcons.calendar,
  .clock => tabler.TablerIcons.clock,
  .users => tabler.TablerIcons.users,
  .upload => tabler.TablerIcons.upload,
  .alertTriangle => tabler.TablerIcons.alertTriangle,
  .info => tabler.TablerIcons.infoCircle,
  .check => tabler.TablerIcons.check,
  .x => tabler.TablerIcons.x,
  .lightbulb => tabler.TablerIcons.bulb,
  .blinds => tabler.TablerIcons.blind,
  .wallet => tabler.TablerIcons.wallet,
  .layoutDashboard => tabler.TablerIcons.layoutDashboard,
  .arrowLeftRight => tabler.TablerIcons.arrowsLeftRight,
  .trendingUp => tabler.TablerIcons.trendingUp,
  .landmark => tabler.TablerIcons.buildingBank,
  .pieChart => tabler.TablerIcons.chartPie,
  .target => tabler.TablerIcons.target,
  .barChart => tabler.TablerIcons.chartBar,
  .fileText => tabler.TablerIcons.fileText,
  .user => tabler.TablerIcons.user,
  .shield => tabler.TablerIcons.shield,
  .paintbrush => tabler.TablerIcons.brush,
  .helpCircle => tabler.TablerIcons.helpCircle,
  .messageSquare => tabler.TablerIcons.message,
  .bookOpen => tabler.TablerIcons.book2,
  .activity => tabler.TablerIcons.activity,
  .circlePlus => tabler.TablerIcons.circlePlus,
  .camera => tabler.TablerIcons.camera,
  .cloud => tabler.TablerIcons.cloud,
  .globe => tabler.TablerIcons.world,
  .gauge => tabler.TablerIcons.gauge,
  .repeat => tabler.TablerIcons.repeat,
  .refreshCw => tabler.TablerIcons.refresh,
};

IconData _remix(PreviewIcon icon) => switch (icon) {
  .home => remix.RemixIcons.home_line,
  .search => remix.RemixIcons.search_line,
  .settings => remix.RemixIcons.settings_3_line,
  .bell => remix.RemixIcons.notification_3_line,
  .plus => remix.RemixIcons.add_line,
  .ellipsis => remix.RemixIcons.more_line,
  .chevronRight => remix.RemixIcons.arrow_right_s_line,
  .play => remix.RemixIcons.play_line,
  .skipForward => remix.RemixIcons.skip_forward_line,
  .music => remix.RemixIcons.music_2_line,
  .coffee => remix.RemixIcons.cup_line,
  .cart => remix.RemixIcons.shopping_cart_2_line,
  .creditCard => remix.RemixIcons.bank_card_line,
  .calendar => remix.RemixIcons.calendar_line,
  .clock => remix.RemixIcons.time_line,
  .users => remix.RemixIcons.group_line,
  .upload => remix.RemixIcons.upload_2_line,
  .alertTriangle => remix.RemixIcons.alert_line,
  .info => remix.RemixIcons.information_line,
  .check => remix.RemixIcons.check_line,
  .x => remix.RemixIcons.close_line,
  .lightbulb => remix.RemixIcons.lightbulb_line,
  .blinds => remix.RemixIcons.window_2_line,
  .wallet => remix.RemixIcons.wallet_3_line,
  .layoutDashboard => remix.RemixIcons.dashboard_line,
  .arrowLeftRight => remix.RemixIcons.arrow_left_right_line,
  .trendingUp => remix.RemixIcons.line_chart_line,
  .landmark => remix.RemixIcons.bank_line,
  .pieChart => remix.RemixIcons.pie_chart_line,
  .target => remix.RemixIcons.target_line,
  .barChart => remix.RemixIcons.bar_chart_2_line,
  .fileText => remix.RemixIcons.file_text_line,
  .user => remix.RemixIcons.user_line,
  .shield => remix.RemixIcons.shield_line,
  .paintbrush => remix.RemixIcons.brush_line,
  .helpCircle => remix.RemixIcons.question_line,
  .messageSquare => remix.RemixIcons.chat_1_line,
  .bookOpen => remix.RemixIcons.book_open_line,
  .activity => remix.RemixIcons.pulse_line,
  .circlePlus => remix.RemixIcons.add_circle_line,
  .camera => remix.RemixIcons.camera_line,
  .cloud => remix.RemixIcons.cloud_line,
  .globe => remix.RemixIcons.global_line,
  .gauge => remix.RemixIcons.dashboard_3_line,
  .repeat => remix.RemixIcons.repeat_line,
  .refreshCw => remix.RemixIcons.refresh_line,
};

Widget _iconoir(PreviewIcon icon, Color color, double size) => switch (icon) {
  .home => iconoir.Home(color: color, width: size, height: size),
  .search => iconoir.Search(color: color, width: size, height: size),
  .settings => iconoir.Settings(color: color, width: size, height: size),
  .bell => iconoir.Bell(color: color, width: size, height: size),
  .plus => iconoir.Plus(color: color, width: size, height: size),
  .ellipsis => iconoir.MoreHoriz(color: color, width: size, height: size),
  .chevronRight => iconoir.NavArrowRight(color: color, width: size, height: size),
  .play => iconoir.Play(color: color, width: size, height: size),
  .skipForward => iconoir.SkipNext(color: color, width: size, height: size),
  .music => iconoir.MusicDoubleNote(color: color, width: size, height: size),
  .coffee => iconoir.CoffeeCup(color: color, width: size, height: size),
  .cart => iconoir.Cart(color: color, width: size, height: size),
  .creditCard => iconoir.CreditCard(color: color, width: size, height: size),
  .calendar => iconoir.Calendar(color: color, width: size, height: size),
  .clock => iconoir.Clock(color: color, width: size, height: size),
  .users => iconoir.Group(color: color, width: size, height: size),
  .upload => iconoir.Upload(color: color, width: size, height: size),
  .alertTriangle => iconoir.WarningTriangle(color: color, width: size, height: size),
  .info => iconoir.InfoCircle(color: color, width: size, height: size),
  .check => iconoir.Check(color: color, width: size, height: size),
  .x => iconoir.Xmark(color: color, width: size, height: size),
  .lightbulb => iconoir.LightBulb(color: color, width: size, height: size),
  .blinds => iconoir.Windows(color: color, width: size, height: size),
  .wallet => iconoir.Wallet(color: color, width: size, height: size),
  .layoutDashboard => iconoir.Dashboard(color: color, width: size, height: size),
  .arrowLeftRight => iconoir.DataTransferBoth(color: color, width: size, height: size),
  .trendingUp => iconoir.GraphUp(color: color, width: size, height: size),
  .landmark => iconoir.Bank(color: color, width: size, height: size),
  .pieChart => iconoir.PercentageCircle(color: color, width: size, height: size),
  .target => iconoir.TriangleFlag(color: color, width: size, height: size),
  .barChart => iconoir.ReportColumns(color: color, width: size, height: size),
  .fileText => iconoir.Page(color: color, width: size, height: size),
  .user => iconoir.User(color: color, width: size, height: size),
  .shield => iconoir.Shield(color: color, width: size, height: size),
  .paintbrush => iconoir.Palette(color: color, width: size, height: size),
  .helpCircle => iconoir.HelpCircle(color: color, width: size, height: size),
  .messageSquare => iconoir.ChatBubble(color: color, width: size, height: size),
  .bookOpen => iconoir.OpenBook(color: color, width: size, height: size),
  .activity => iconoir.Activity(color: color, width: size, height: size),
  .circlePlus => iconoir.PlusCircle(color: color, width: size, height: size),
  .camera => iconoir.Camera(color: color, width: size, height: size),
  .cloud => iconoir.Cloud(color: color, width: size, height: size),
  .globe => iconoir.Globe(color: color, width: size, height: size),
  .gauge => iconoir.DashboardSpeed(color: color, width: size, height: size),
  .repeat => iconoir.Repeat(color: color, width: size, height: size),
  .refreshCw => iconoir.Refresh(color: color, width: size, height: size),
};
