minimumReleaseAge: 4320 # 3 days
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  # Renovate security update: next@16.2.11
  - next@16.2.11
